import { motion } from "framer-motion"
import {
  FaUpload,
  FaCalendarAlt,
  FaBook,
  FaQuestionCircle,
  FaChartLine,
} from "react-icons/fa"

const steps = [
  {
    icon: <FaUpload size={32} />,
    title: "Upload Syllabus",
    description:
      "Upload your syllabus or choose a topic to get started.",
    color: "text-cyan-400",
  },
  {
    icon: <FaCalendarAlt size={32} />,
    title: "AI Study Planner",
    description:
      "NeuroLearn creates a personalized daily study plan.",
    color: "text-green-400",
  },
  {
    icon: <FaBook size={32} />,
    title: "Learn & Revise",
    description:
      "Generate notes and revise with interactive flashcards.",
    color: "text-purple-400",
  },
  {
    icon: <FaQuestionCircle size={32} />,
    title: "Practice",
    description:
      "Take adaptive quizzes generated by AI.",
    color: "text-yellow-400",
  },
  {
    icon: <FaChartLine size={32} />,
    title: "Track Progress",
    description:
      "Monitor your accuracy and improve weak topics.",
    color: "text-pink-400",
  },
]

function HowItWorks() {
  return (
    <section className="bg-[#020617] py-28 px-8">

      <div className="max-w-7xl mx-auto">

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-20"
        >
          <h2 className="text-5xl font-bold text-white">
            How
            <span className="text-cyan-400">
              {" "}NeuroLearn
            </span>
            {" "}Works
          </h2>

          <p className="text-gray-400 mt-6 text-lg max-w-3xl mx-auto">
            From planning your studies to tracking your progress,
            NeuroLearn guides you through every step of your learning journey.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-5 gap-8">

          {steps.map((step, index) => (

            <motion.div
              key={step.title}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{
                delay: index * 0.15,
              }}
              viewport={{ once: true }}
              whileHover={{
                y: -8,
              }}
              className="relative bg-slate-900 border border-slate-800 rounded-3xl p-6 text-center"
            >

              <div className={`${step.color} flex justify-center mb-5`}>
                {step.icon}
              </div>

              <div className="w-10 h-10 rounded-full bg-cyan-500 text-black font-bold flex items-center justify-center mx-auto mb-5">
                {index + 1}
              </div>

              <h3 className="text-xl font-semibold text-white">
                {step.title}
              </h3>

              <p className="text-gray-400 mt-4">
                {step.description}
              </p>

            </motion.div>

          ))}

        </div>

      </div>

    </section>
  )
}

export default HowItWorks